# Generated by Django 3.0.5 on 2020-08-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_jjim'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=1000)),
                ('img', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Jjim',
        ),
    ]
